# features.py — FairCredit 2.0
# Auto-generated by Person 1. Do not edit manually.

FEATURE_NAMES = ['Age', 'AnnualIncome', 'CreditScore', 'Experience', 'LoanAmount', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'CreditCardUtilizationRate', 'NumberOfOpenCreditLines', 'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory', 'PreviousLoanDefaults', 'PaymentHistory', 'LengthOfCreditHistory', 'SavingsAccountBalance', 'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities', 'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth', 'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment', 'TotalDebtToIncomeRatio', 'MissedPaymentFlag', 'HighUtilizationFlag', 'SavingsToLoanRatio', 'EmploymentStatus_Self-Employed', 'EmploymentStatus_Unemployed', 'EducationLevel_Bachelor', 'EducationLevel_Doctorate', 'EducationLevel_High School', 'EducationLevel_Master', 'MaritalStatus_Married', 'MaritalStatus_Single', 'MaritalStatus_Widowed', 'HomeOwnershipStatus_Other', 'HomeOwnershipStatus_Own', 'HomeOwnershipStatus_Rent', 'LoanPurpose_Debt Consolidation', 'LoanPurpose_Education', 'LoanPurpose_Home', 'LoanPurpose_Other']

TARGET = 'LoanApproved'

PROTECTED_ATTRS = ['Age', 'AgeGroup', 'MaritalStatus']

ENGINEERED_FEATURES = [
    'MissedPaymentFlag',    # 1 if PreviousLoanDefaults > 0
    'HighUtilizationFlag',  # 1 if CreditCardUtilizationRate > 0.75
    'SavingsToLoanRatio',   # SavingsAccountBalance / LoanAmount
    'EMIBurdenRatio',       # MonthlyDebt / MonthlyIncome (cohort analysis)
]

FEATURE_DESCRIPTIONS = {
    'CreditScore':              'Credit score (higher = more creditworthy)',
    'AnnualIncome':             'Annual income of the applicant',
    'MonthlyIncome':            'Monthly income',
    'LoanAmount':               'Loan amount requested',
    'LoanDuration':             'Loan duration in months',
    'DebtToIncomeRatio':        'Total debt as a fraction of annual income',
    'CreditCardUtilizationRate':'Fraction of credit card limit currently used',
    'PreviousLoanDefaults':     'Number of previous loan defaults',
    'MissedPaymentFlag':        '1 if applicant has any previous loan default',
    'HighUtilizationFlag':      '1 if credit utilization exceeds 75%',
    'SavingsToLoanRatio':       'Savings buffer relative to loan size',
    'EMIBurdenRatio':           'Monthly debt obligations as fraction of monthly income',
    'TotalDebt':                'Total outstanding debt',
    'TotalAssets':              'Total assets owned by applicant',
    'NetWorth':                 'Net worth (Assets minus Liabilities)',
    'JobTenure':                'Years at current job',
    'PaymentHistory':           'Historical payment performance score',
    'LengthOfCreditHistory':    'How long the applicant has had credit accounts',
    'BankruptcyHistory':        'Whether the applicant has declared bankruptcy',
    'NumberOfDependents':       'Number of financial dependents',
    'Experience':               'Total work experience in years',
    'BaselineInterestRate':     'Market baseline interest rate at application time',
    'MonthlyDebt':              'Monthly debt repayment obligations',
    'MonthlyExpenses':          'Total monthly expenses',
    'UtilityBills':             'Monthly utility bill amount',
}
